### ISSUE TITLE
Barebones SPI wiring?

### ISSUE THREAD

**Issue by kdharbert** [sparkfun/SparkFun_BNO080_Arduino_Library#79]
I have a BNO08x working with SPI and it requires 9 connections. I have a simple use case where the BNO08x is immediately initialized, runs constantly and is the only device on that SPI bus. Is there any chance I could simplify the wiring to use only 8 total connections?  

The driving use case is that I need to mount it to a Teensy 4.1 neatly.  I can easily make a dummy microSD adapter that can map the 8 microSD card adapter pins on the Teensy to the the BNO08x. You can then just insert the unit into the onboard microSD slot on the Teensy.  However, I need to salvage one pin from the BNO08x config to make it work.  

The microSD port has VCC,GND,SCK,MISO,MOSI and 3xDigital ports.  In SPI mode, the BNO08x requires CS,RST,INT and WAKPIN...which requires 4 digital pins and I only have three available.  If the simplistic use case allows for saving one wire one the BNO08x, I can make this work.  Any chance this is possible?

**Comment by PaulZC** [comment]
Hi @kdharbert ,

Please note, we now try to use the acronyms [CIPO and COPI](https://www.oshwa.org/2020/06/29/a-resolution-to-redefine-spi-pin-names/) for the SPI data pins.

You definitely need the Chip Select pin, even if the BNO is the only thing on the bus.

Looking at the datasheet:

It does say that WAKE must be connected in order to bring the BNO out of sleep:
"Pin 6 must be connected to a GPIO so that the WAKE functionality can be performed."
"When the host want to initiate contact with the BNO08X it may be necessary to wake the processor from a sleep
mode. To enable this function the BNO08X uses the PS0/wake pin."

"The H_INTN pin is the application interrupt line that indicates the BNO08X requires attention."
"if the host fails to respond to the assertion of H_INTN, the BNO080 will eventually reset due to a
watchdog timeout."
So, I guess you're stuck there.

I guess your only possibility is the RESET pin. I would recommend trying connecting the RESET pin to a reset supervisor chip, to ensure the chip is properly reset when power is applied. There are plenty of options in terms of the threshold voltage, push-pull output vs. open-drain, and reset hold time delay. Something like the Microchip MCP103-300 should do nicely. It is available in SC70, SOT-23 and good old TO-92 packaging.
Best wishes,
Paul
